In [10]:
using Pkg
#Pkg.add("DataFrames")
#Pkg.add("Plots")
#Pkg.add("PyCall")
#Pkg.add("Conda")
using DataFrames
using Plots
using Conda
#Conda.add("Seaborn")
using Seaborn
using Random

In [19]:
#Make a deck
function make_decks(num_decks,card_types)
    new_deck = []
    for i ∈ 1:length(num_decks)
        for j ∈ 1:4
            append!(new_deck,card_types)
        end
    end
    Random.shuffle!(new_deck)
    return new_deck
end

make_decks (generic function with 1 method)

In [26]:
set = [1,2,3,4,5,6,7,8,9,10,10,10,10]
deck = make_decks(1,set)
println(deck)
println(length(deck))

Any[9, 10, 8, 5, 10, 2, 9, 4, 2, 10, 4, 10, 6, 9, 2, 9, 10, 3, 1, 7, 10, 8, 10, 7, 5, 1, 3, 5, 6, 6, 3, 7, 3, 5, 4, 10, 1, 6, 4, 10, 2, 10, 7, 10, 10, 8, 10, 1, 10, 8, 10, 10]
52


In [449]:
#aces can be either 1 or 11
function possible(aces)
    
    if aces == 0
        return 0,[[0,0]]
    else
        choices = aces[1]
        x = length(choices)
        full_length = x^length(aces)
        sum_array = zeros(full_length,length(aces))

        for i ∈ 1:length(aces)
            n = length(aces) - (i-1) 
            split_len = Int(full_length/(x^i))

            for j ∈ 0: x^(i-1)-1
                sum_array[j*x^n+1 : j*x^n + split_len ,i] .= choices[1]
                sum_array[j*x^n+1 + split_len : j*x^n + split_len*2 ,i] .= choices[2]
            end

        end

        empty = []
        emptybox = []

        for k ∈ 1:length(sum_array[:,1])
            if sum(sum_array[k,:]) <= 21
                append!(emptybox,[sum_array[k,:]])
                append!(empty,sum(sum_array[k,:]))
            end
        end

        return empty,emptybox
    end
end

function aces(num_aces)
    
    if num_aces == 0
        return 0
    else
        temp_list = []
        for i ∈ 1:num_aces
            append!(temp_list,[[1,11]])
        end

        return temp_list
    end
    
end

aces (generic function with 1 method)

In [453]:
println(possible(aces(1))[1:2][2])
a,b = possible(aces(0))
println(length((a)))
println(a[1])
println(b)

Any[[1.0], [11.0]]
1
0
[[0, 0]]


In [454]:
# total value of a hand
function total_up(hand)
    
    ace_count = 0
    total = 0
    
    for i ∈ hand
        if i != 'A'
            total += i
        else
            ace_count += 1
        end
    end
    
    ace_value_list,_ = possible(aces(ace_count))
    final_totals = []
    
    for j ∈ 1:length(ace_value_list)
        if ace_value_list[j] + total <= 21
            append!(final_totals, ace_value_list[j] + total)
        end
    end
    
    if final_totals == []
        return minimum(ace_value_list .+ total)
    elseif total > 21
        return minimum(ace_value_list .+ total)
    else
        return maximum(final_totals)
    end
    
end

total_up (generic function with 1 method)

In [463]:
hand = ['A',2,3,4]
ace_count = 0
total = 0

for i ∈ hand
    #print(i)
    if i != 'A'
        total += i
    else
        ace_count += 1
    end
end

ace_value_list,_ = possible(aces(ace_count))
final_totals = []

for j ∈ 1:length(ace_value_list)
    if ace_value_list[j] + total <= 21
        append!(final_totals, ace_value_list[j] + total)
    end
end

println(ace_value_list)

# print(final_totals)



Any[1.0, 11.0]


In [462]:
total_up([2,3,4,5,10])

24

In [243]:
#Make a deck
function make_decks(num_decks,card_types)
    new_deck = []
    for i ∈ 1:length(num_decks)
        for j ∈ 1:4
            append!(new_deck,card_types)
        end
    end
    Random.shuffle!(new_deck)
    return new_deck
end

make_decks (generic function with 1 method)

In [245]:
make_decks(1,['A',2,3,4,5,6,7,8,9,10,10,10,10])

52-element Vector{Any}:
  6
  4
  2
  4
  2
  7
 10
 10
 10
  5
  6
 10
  9
  ⋮
  6
  2
 10
 10
  8
  9
  5
   'A': ASCII/Unicode U+0041 (category Lu: Letter, uppercase)
  2
  8
 10
 10

In [483]:
stacks = 1
players = Int(input("How many players?"))
num_decks = 1
five_card_win = true
gaming = 0
correctness = 0
player_names = []

while gaming != "Y" || "N" && correctness != "Y"
    gaming = strip(uppercase(input("Will there be real players: yes or no?")))[1]
    
    if gaming == "Y" 
        while correctness != "Y" || "N"
            correctness = strip(uppercase(input("There are real players. Is this correct: yes or no?")))[1]
        end
    elseif gaming == "N"
        while correctness != "Y" || "N"
            correctness = strip(uppercase(input("There are no real players. Is this correct: yes or no?")))[1]
        end
    end
    

end

if gaming == "Y"
   for i ∈ 1:players
        correct_name = 0
        while correct_name != "Y"
            name = input("Name of player ",i,"?")
            correct_name = strip(uppercase(input("Is this name correct: yes or no?")))[1]
        end
        append!(player_names,name)
end
    

card_types = ['A',2,3,4,5,6,7,8,9,10,10,10,10]

#blackjack = Set(['A',10])
# bl_1 = ['A',10]
# bl_2 = [10,'A']
# bl_1 = convert(Vector{Any},bl_1)
# bl_2 = convert(Vector{Any},bl_2)

for stack ∈ 1:stacks
    
    dealer_cards = make_decks(num_decks,card_types)
    
    
    while length(dealer_cards) > 20
        
        current_players = 3*ones(1,players)
        
        dealer_hand = []
        player_hands = [[] for player ∈ 1:players]
#         dealer_hand = convert(Vector{Any},dealer_hand)
#         player_hands = convert(Vector{Any},player_hands)
        
        #Deal First card
        
        for i ∈ 1:players
            append!(player_hands[i],dealer_cards[1])
            popfirst!(dealer_cards)
        end
        append!(dealer_hand,dealer_cards[1])
        popfirst!(dealer_cards)
        
        #Deal Second card
        
        for i ∈ 1:players
            append!(player_hands[i],dealer_cards[1])
            popfirst!(dealer_cards)
        end
        append!(dealer_hand,dealer_cards[1])
        popfirst!(dealer_cards)
        
        
        cards_dealt = 2
        
        #Check for 21

        #println("Dealer hand initially: ",dealer_hand)
        println("Player hands initially:")
        println([player_names; player_hands)
            
        
        
        if total_up(dealer_hand) == 21 #blackjack #['A',10] || [10,'A']
            for j ∈ 1:players
                if total_up(player_hands[j]) != 21 #['A',10] || [10,'A']
                    current_players[j] = -1
                else
                    current_players[j] = 0
                end
            end
            
        else
            
            for k ∈ 1:players
                if total_up(player_hands[k]) == 21 #blackjack #['A',10] || [10,'A']
                    current_players[k] = 1
                end
            end
            
            
            while cards_dealt < 5
                cards_dealt += 1
                for z ∈ 1:players
                    if current_players[z] > 2
                        ran_number = rand()
                        if total_up(player_hands[z]) <= 11
                            append!(player_hands[z],dealer_cards[1])
                            popfirst!(dealer_cards)
                        else
                            if gaming == "N"
                                if ran_number < 0.5
                                    current_players[z] = 0
                                else
                                    #println(ran_number)
                                    append!(player_hands[z],dealer_cards[1])
                                    popfirst!(dealer_cards)
                                    #println(player_hands[z])
                                end
                            else
                                decision = 0
                                while decision != "Y" || "N"
                                    decision = strip(uppercase(input
                                    ("Draw another card ",player_name[z],": yes or no?")))[1]
                                end
                                if decision == "N"
                                    current_players[z] = 0
                                else
                                    append!(player_hands[z],dealer_cards[1])
                                    popfirst!(dealer_cards)
                                end
                            end
                                    

                        end
                    end

                    if total_up(player_hands[z]) == 21
                        current_players[z] = 0
                    end

                    if total_up(player_hands[z]) > 21
                        current_players[z] = -1
                    end

                end
            end
        
            
            
            if five_card_win == true
                for n ∈ 1:players
                    if length(player_hands[n]) == 5 && current_players[n] != -1
                        current_players[n] = 1
                    end
                end
            end

            # dealer hits until bust or at least 17

            while total_up(dealer_hand) < 17
                append!(dealer_hand,dealer_cards[1])
                popfirst!(dealer_cards)
            end

            if total_up(dealer_hand) > 21
                for l ∈ 1:players
                    if current_players[l] != -1
                        current_players[l] = 1
                    end
                end
            else
                for m ∈ 1:players
                    if current_players[m] != 1
                        if total_up(player_hands[m]) > total_up(dealer_hand)
                            current_players[m] = 1
                        elseif total_up(player_hands[m]) == total_up(dealer_hand)
                            current_players[m] = 0
                        else
                            current_players[m] = -1
                        end
                    end
                end
            end
            
            
            
        end
        
        println()
        println("Dealer hand: ",dealer_hand)
        println("Player hands: ",player_hands)
        
        println("Result: ",current_players)
        println("--------------------------------------------------------")
        println()
                        
        
    end

end




LoadError: UndefVarError: input not defined

In [219]:
zeros(2,3)

2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [220]:
zeros(2,2,2,2)

2×2×2×2 Array{Float64, 4}:
[:, :, 1, 1] =
 0.0  0.0
 0.0  0.0

[:, :, 2, 1] =
 0.0  0.0
 0.0  0.0

[:, :, 1, 2] =
 0.0  0.0
 0.0  0.0

[:, :, 2, 2] =
 0.0  0.0
 0.0  0.0

In [37]:
zeros(length=3,dims = 3)

LoadError: MethodError: no method matching zeros(; length=3, dims=3)
Closest candidates are:
  zeros(::Tuple{Vararg{Union{Integer, AbstractUnitRange}}}) at /opt/julia-1.7.2/share/julia/base/array.jl:522 got unsupported keyword arguments "length", "dims"
  zeros(::Type{StaticArrays.MVector{N}}) where N at ~/.julia/packages/StaticArrays/12k3X/src/MVector.jl:25 got unsupported keyword arguments "length", "dims"
  zeros(::Type{StaticArrays.SVector{N}}) where N at ~/.julia/packages/StaticArrays/12k3X/src/SVector.jl:32 got unsupported keyword arguments "length", "dims"
  ...

In [48]:
x = zeros(2,2)
x[1,1] = 1
print(x)

[1.0 0.0; 0.0 0.0]

In [59]:
Int(2^1 * 0.5)

1

In [136]:
a = [1 2 3; 4 5 6]
#print(length(a))
b = a[a.>3]

# print(a)

# c = sum(a)

# print(b)
# print(c)





for i ∈ a
    println(i)
end

1
4
2
5
3
6


In [96]:
c = 1:10
sum(c)

55

In [119]:
t= ones(2,3)
print(t[1,:])

[1.0, 1.0, 1.0]

In [146]:
a = [[2 3 4] ;[1 2 3]]
print(a)

[2 3 4; 1 2 3]

In [364]:
c = [1,2,3]
d  = make_decks(1,c)
println(d)
for i ∈ 1:7
    popfirst!(d)
    println(d[1])
end

Any[1, 2, 1, 1, 3, 2, 2, 1, 3, 3, 2, 3]
2
1
1
3
2
2
1


In [191]:
players = 3
dealer_hands = [[] for player ∈ 1:players]
print(dealer_hands)

println(enumerate(dealer_hands[player]))

Vector{Any}[[], [], []]

LoadError: UndefVarError: player not defined

In [188]:
enumerate([3,4][1])
z = [3,4]
print(typeof(z))
z = convert(Vector{Any},z)
append!(z,[[]])
print(z)

Vector{Int64}Any[3, 4, Any[]]

In [194]:
z = [3,4]
popfirst!(z)
print(z)

[4]

In [203]:
3*ones(1,4)

1×4 Matrix{Float64}:
 3.0  3.0  3.0  3.0

In [211]:
a = 'A'
if a == 'A'
    print("true")
end

true

In [241]:
blackjack = Set(['A',10])
z = ['A',10]
if ['A',10] == blackjack
    print("true")
elseif [10,'A'] == blackjack
    print("false")
elseif 10 == blackjack
    print("yes")
elseif 'A' == blackjack
    print("no")
elseif z == blackjack
    print(z)
    
end
    
        
println(blackjack)


for i in blackjack
    println(i)
end

Set(Any['A', 10])
A
10


In [397]:
stacks = 1
players = 2
num_decks = 1
five_card_win = true

card_types = ['A',2,3,4,5,6,7,8,9,10,10,10,10]

#blackjack = Set(['A',10])
# bl_1 = ['A',10]
# bl_2 = [10,'A']
# bl_1 = convert(Vector{Any},bl_1)
# bl_2 = convert(Vector{Any},bl_2)


    
dealer_cards = make_decks(num_decks,card_types)

println(length(dealer_cards))
popfirst!(dealer_cards)
println(length(dealer_cards))

# current_players = 3*ones(1,players)



# dealer_hand = []
# player_hands = [[] for player ∈ 1:players]
# #         dealer_hand = convert(Vector{Any},dealer_hand)
# #         player_hands = convert(Vector{Any},player_hands)

# #Deal First card

# for i ∈ 1:players
#     append!(player_hands[i],dealer_cards[1])
#     popfirst!(dealer_cards)
# end
# append!(dealer_hand,dealer_cards[1])
# popfirst!(dealer_cards)


# println(player_hands)

# #Deal Second card

# for i ∈ 1:players
#     append!(player_hands[i],dealer_cards[1])
#     popfirst!(dealer_cards)
# end
# append!(dealer_hand,dealer_cards[1])
# popfirst!(dealer_cards)

# cards_dealt = 2

# #Check for 21
# #print(dealer_hand)

# println(player_hands)

# # if total_up(dealer_hand) == 21 #blackjack #['A',10] || [10,'A']
# #     for j ∈ 1:players
# #         if total_up(player_hands[j]) != 21 #['A',10] || [10,'A']
# #             current_players[1,j] = -1
# #         else
# #             current_players[1,j] = 0
# #         end
# #     end
# # end


# for z ∈ 1:players
#     ran_number = rand()
#     print(ran_number)
#     if ran_number > 0.5
#         append!(player_hands[z],dealer_cards[1])
#         popfirst!(dealer_cards)
#     else
#         current_players[z] = 0
#     end
# end

# print(current_players)

52
51


In [396]:
current_players = 3*ones(1,3)
print(current_players[3])
print(length(current_players))


if ran_number > 0.5
    append!(player_hands[z],dealer_cards[1])
    popfirst!(dealer_cards)
else
    current_players[z] = 0
end

3.03

LoadError: UndefVarError: ran_number not defined

In [323]:
rand()

0.9112387876817758

In [482]:
print(uppercase("     hello i am retard "))
strip("     hello i am retard ")[1]


     HELLO I AM RETARD 

'h': ASCII/Unicode U+0068 (category Ll: Letter, lowercase)

In [486]:
print(input("henlo"))

LoadError: UndefVarError: input not defined

In [4]:
function input(prompt::AbstractString="")
    print(prompt)
    return chomp(readline())
end

input (generic function with 2 methods)

In [5]:
input("Enter your name: ")

stdin> 30
Enter your name: 

"30"

In [4]:
print("Enter your name")
Input("Enter your name")

stdin> henlo
Enter your nameYour name is henlo

In [1]:
sayhi(name) = println("Hi $name, how are you?")

sayhi (generic function with 1 method)

In [2]:
sayhi("dog")

Hi dog, how are you?


In [10]:
begin
    println("Write your name")
    name = readline()
    println("Who is $name")
end

stdin> duck
Write your name
Who is duck
